EnergyConsumptionRationing/Models/TypesProduction.cs
namespace EnergyConsumptionRationing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TypesProduction")]
    public partial class TypesProduction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypesProduction()
        {
            ConsumedRelease = new HashSet<ConsumedRelease>();
            ReleaseProducts = new HashSet<ReleaseProducts>();
            StandartExpense = new HashSet<StandartExpense>();
        }

        [Key]
        public int ProductionID { get; set; }

        [StringLength(30)]
        public string ProductionName { get; set; }

        [StringLength(15)]
        public string MeasureUnit { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumedRelease> ConsumedRelease { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseProducts> ReleaseProducts { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandartExpense> StandartExpense { get; set; }
    }
}

EnergyConsumptionRationing/Controllers/TypesProductionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnergyConsumptionRationing.Models;
using PagedList;

namespace EnergyConsumptionRationing.Controllers
{
    public class TypesProductionsController : Controller
    {
        private EnergyContext db = new EnergyContext();

        // GET: TypesProductions
        public ActionResult Index(int? page, string Search = "")
        {
            var query = from tp in db.TypesProduction
                        where tp.ProductionName.StartsWith(Search)
                        select tp;
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var sotrorder = query.OrderBy(t => t.ProductionID);
            return View(sotrorder.ToPagedList(pageNumber, pageSize));
        }

        // GET: TypesProductions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypesProduction typesProduction = db.TypesProduction.Find(id);
            if (typesProduction == null)
            {
                return HttpNotFound();
            }
            return View(typesProduction);
        }

        // GET: TypesProductions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TypesProductions/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductionID,ProductionName,MeasureUnit")] TypesProduction typesProduction)
        {
            if (ModelState.IsValid)
            {
                db.TypesProduction.Add(typesProduction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(typesProduction);
        }

        // GET: TypesProductions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypesProduction typesProduction = db.TypesProduction.Find(id);
            if (typesProduction == null)
            {
                return HttpNotFound();
            }
            return View(typesProduction);
        }

        // POST: TypesProductions/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductionID,ProductionName,MeasureUnit")] TypesProduction typesProduction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(typesProduction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(typesProduction);
        }

        // GET: TypesProductions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypesProduction typesProduction = db.TypesProduction.Find(id);
            if (typesProduction == null)
            {
                return HttpNotFound();
            }
            return View(typesProduction);
        }

        // POST: TypesProductions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TypesProduction typesProduction = db.TypesProduction.Find(id);
            db.TypesProduction.Remove(typesProduction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnergyConsumptionRationing/Views/TypesProductions/Create.cshtml
@model EnergyConsumptionRationing.Models.TypesProduction

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить запись</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <dl class="dl-horizontal">
            <dt>Наименование продукции</dt>
            <dd>
                @Html.EditorFor(model => model.ProductionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductionName, "", new { @class = "text-danger" })
            </dd>

            <dt>Единица измерения</dt>
            <dd>
                @Html.EditorFor(model => model.MeasureUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeasureUnit, "", new { @class = "text-danger" })
            </dd>
        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnergyConsumptionRationing/Views/TypesProductions/Delete.cshtml
@model EnergyConsumptionRationing.Models.TypesProduction

@{
    ViewBag.Title = "Удалить";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Вы уверены, что хотите удалить запись?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Наименование продукции</dt>
        <dd>@Html.DisplayFor(model => model.ProductionName)</dd>

        <dt>Единица измерения</dt>
        <dd>@Html.DisplayFor(model => model.MeasureUnit)</dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    }
</div>

EnergyConsumptionRationing/Views/TypesProductions/Details.cshtml
@model EnergyConsumptionRationing.Models.TypesProduction

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Детали</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Наименование продукции</dt>
        <dd>@Html.DisplayFor(model => model.ProductionName)</dd>

        <dt>Единица измерения</dt>
        <dd>@Html.DisplayFor(model => model.MeasureUnit)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать запись", "Edit", new { id = Model.ProductionID }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>

EnergyConsumptionRationing/Views/TypesProductions/Edit.cshtml
@model EnergyConsumptionRationing.Models.TypesProduction

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактировать</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductionID)

        <dl class="dl-horizontal">
            <dt>Наименование продукции</dt>
            <dd>
                @Html.EditorFor(model => model.ProductionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductionName, "", new { @class = "text-danger" })
            </dd>

            <dt>Единица измерения</dt>
            <dd>
                @Html.EditorFor(model => model.MeasureUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeasureUnit, "", new { @class = "text-danger" })
            </dd>
        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnergyConsumptionRationing/Views/TypesProductions/Index.cshtml
@model PagedList.IPagedList<EnergyConsumptionRationing.Models.TypesProduction>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("/Content/PagedList.css")" rel="stylesheet" type="text/css" />

<h2>Виды продукции</h2>

@using (Html.BeginForm("Index", "TypesProductions", FormMethod.Get))
{
    <fieldset>
        <h3 style="font-size:14px">Поиск по наименованию продукции:</h3>&nbsp;@Html.TextBox("Search", "")
        <input type="submit" value="Поиск"/>
    </fieldset>
}
<br/>

<p style="color:black">
    @Html.ActionLink("Добавить запись", "Create")
</p>
<table class="table-bordered" cellpadding="5" width="100%" align="center" style="font-size:14px;">
    <tr>
        <th> Код </th>
        <th> Название продукции </th>
        <th> Единица измерения </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td><p>@Html.DisplayFor(modelItem => item.ProductionID)</p></td>
        <td><p>@Html.DisplayFor(modelItem => item.ProductionName)</p></td>
        <td><p>@Html.DisplayFor(modelItem => item.MeasureUnit)</p></td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id = item.ProductionID }) |
            @Html.ActionLink("Детали", "Details", new { id = item.ProductionID }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.ProductionID })
        </td>
    </tr>
}
</table>

<div style="text-align: center;">
    Страница @(Model.PageCount < Model.PageNumber ? 0:Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page}))
</div>