EnergyConsumptionRationing/Models/ReleaseProducts.cs
namespace EnergyConsumptionRationing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class ReleaseProducts
    {
        [Key]
        public int ReleaseID { get; set; }

        public int? ProductionID { get; set; }

        [Range(1, 10000000000, ErrorMessage = "The data is incorrect")]
        public int? TotalRelease { get; set; }

        [Range(1800,2016,ErrorMessage ="The data is incorrect")]
        public int? Year { get; set; }

        [Range(1, 4, ErrorMessage = "The data is incorrect")]
        public int? Quarter { get; set; }

        public int? OrganizationID { get; set; }

        public virtual Organization Organization { get; set; }

        public virtual TypesProduction TypesProduction { get; set; }
    }
}

EnergyConsumptionRationing/Controllers/ReleaseProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnergyConsumptionRationing.Models;
using PagedList;

namespace EnergyConsumptionRationing.Controllers
{
    public class ReleaseProductsController : Controller
    {
        private EnergyContext db = new EnergyContext();

        // GET: ReleaseProducts
        public ActionResult Index(int? page, string SearchOne = "", string SearchTwo  = "")
        {
            var query = from i in db.ReleaseProducts
                        where i.TypesProduction.ProductionName.StartsWith(SearchOne) && i.Organization.OrganizationName.StartsWith(SearchTwo)
                        select i;
            int PageSize = 10;
            int pageNumber = (page ?? 1);
            var sotorder = query.OrderBy(im => im.ReleaseID);
            return View(sotorder.ToPagedList(pageNumber, PageSize));
        }

        // GET: ReleaseProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReleaseProducts releaseProducts = db.ReleaseProducts.Find(id);
            if (releaseProducts == null)
            {
                return HttpNotFound();
            }
            return View(releaseProducts);
        }

        // GET: ReleaseProducts/Create
        public ActionResult Create()
        {
            ViewBag.OrganizationID = new SelectList(db.Organization, "OrganizationID", "OrganizationName");
            ViewBag.ProductionID = new SelectList(db.TypesProduction, "ProductionID", "ProductionName");
            return View();
        }

        // POST: ReleaseProducts/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReleaseID,ProductionID,TotalRelease,Year,Quarter,OrganizationID")] ReleaseProducts releaseProducts)
        {
            if (ModelState.IsValid)
            {
                db.ReleaseProducts.Add(releaseProducts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OrganizationID = new SelectList(db.Organization, "OrganizationID", "OrganizationName", releaseProducts.OrganizationID);
            ViewBag.ProductionID = new SelectList(db.TypesProduction, "ProductionID", "ProductionName", releaseProducts.ProductionID);
            return View(releaseProducts);
        }

        // GET: ReleaseProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReleaseProducts releaseProducts = db.ReleaseProducts.Find(id);
            if (releaseProducts == null)
            {
                return HttpNotFound();
            }
            ViewBag.OrganizationID = new SelectList(db.Organization, "OrganizationID", "OrganizationName", releaseProducts.OrganizationID);
            ViewBag.ProductionID = new SelectList(db.TypesProduction, "ProductionID", "ProductionName", releaseProducts.ProductionID);
            return View(releaseProducts);
        }

        // POST: ReleaseProducts/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReleaseID,ProductionID,TotalRelease,Year,Quarter,OrganizationID")] ReleaseProducts releaseProducts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(releaseProducts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OrganizationID = new SelectList(db.Organization, "OrganizationID", "OrganizationName", releaseProducts.OrganizationID);
            ViewBag.ProductionID = new SelectList(db.TypesProduction, "ProductionID", "ProductionName", releaseProducts.ProductionID);
            return View(releaseProducts);
        }

        // GET: ReleaseProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReleaseProducts releaseProducts = db.ReleaseProducts.Find(id);
            if (releaseProducts == null)
            {
                return HttpNotFound();
            }
            return View(releaseProducts);
        }

        // POST: ReleaseProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ReleaseProducts releaseProducts = db.ReleaseProducts.Find(id);
            db.ReleaseProducts.Remove(releaseProducts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnergyConsumptionRationing/Views/ReleaseProducts/Create.cshtml
@model EnergyConsumptionRationing.Models.ReleaseProducts

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить запись</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <dl class="dl-horizontal">
            <dt>Название организации</dt>
            <dd>
                @Html.DropDownList("OrganizationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganizationID, "", new { @class = "text-danger" })
            </dd>

            <dt>Наименование продукции</dt>
            <dd>
                @Html.DropDownList("ProductionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductionID, "", new { @class = "text-danger" })
            </dd>

            <dt>Всего произведено</dt>
            <dd>
                @Html.EditorFor(model => model.TotalRelease, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalRelease, "", new { @class = "text-danger" })
            </dd>

            <dt>Год(с 1800 до 2016)</dt>
            <dd>
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </dd>

            <dt>Кварал</dt>
            <dd>
                @Html.EditorFor(model => model.Quarter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quarter, "", new { @class = "text-danger" })
            </dd>
        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить запись" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnergyConsumptionRationing/Views/ReleaseProducts/Delete.cshtml
@model EnergyConsumptionRationing.Models.ReleaseProducts

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Вы уверены, что хотите удалить запись?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Название организации</dt>
        <dd>@Html.DisplayFor(model => model.Organization.OrganizationName)</dd>

        <dt>Наименование продукции</dt>
        <dd>@Html.DisplayFor(model => model.TypesProduction.ProductionName)</dd>

        <dt>Всего произведено</dt>
        <dd>@Html.DisplayFor(model => model.TotalRelease)</dd>

        <dt>Год</dt>
        <dd>@Html.DisplayFor(model => model.Year)</dd>

        <dt>Кварал</dt>
        <dd>@Html.DisplayFor(model => model.Quarter)</dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    }
</div>

EnergyConsumptionRationing/Views/ReleaseProducts/Details.cshtml
@model EnergyConsumptionRationing.Models.ReleaseProducts

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Детали</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Название организации</dt>
        <dd>@Html.DisplayFor(model => model.Organization.OrganizationName)</dd>

        <dt>Наименование продукции</dt>
        <dd>@Html.DisplayFor(model => model.TypesProduction.ProductionName)</dd>

        <dt>Всего произведено</dt>
        <dd>@Html.DisplayFor(model => model.TotalRelease)</dd>

        <dt>Год</dt>
        <dd>@Html.DisplayFor(model => model.Year)</dd>

        <dt>Квартал</dt>
        <dd>@Html.DisplayFor(model => model.Quarter)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать запись", "Edit", new { id = Model.ReleaseID }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>

EnergyConsumptionRationing/Views/ReleaseProducts/Edit.cshtml
@model EnergyConsumptionRationing.Models.ReleaseProducts

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактировать запись</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ReleaseID)

        <dl class="dl-horizontal">
            <dt>Название организации</dt>
            <dd>
                @Html.DropDownList("OrganizationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganizationID, "", new { @class = "text-danger" })
            </dd>

            <dt>Наименование продукции</dt>
            <dd>
                @Html.DropDownList("ProductionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductionID, "", new { @class = "text-danger" })
            </dd>

            <dt>Всего произведено</dt>
            <dd>
                @Html.EditorFor(model => model.TotalRelease, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalRelease, "", new { @class = "text-danger" })
            </dd>

            <dt>Год(с 1800 до 2016)</dt>
            <dd>
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </dd>

            <dt>Кварал</dt>
            <dd>
                @Html.EditorFor(model => model.Quarter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quarter, "", new { @class = "text-danger" })
            </dd>
        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnergyConsumptionRationing/Views/ReleaseProducts/Index.cshtml
@model PagedList.IPagedList<EnergyConsumptionRationing.Models.ReleaseProducts>
    @using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("/Content/PageList.css")" rel = "stylesheet" type = "text/css"/>

<h2>Произведено продукции</h2>

@using (Html.BeginForm("Index", "ReleaseProducts", FormMethod.Get))
{
    <fieldset>
        <h3 style="font-size:14px">Поиск по наименованию продукции:</h3>&nbsp;@Html.TextBox("SearchOne", "")
        <input type="submit" value="Поиск"/>
        &ensp;
        <h3 style="font-size:14px">Поиск по названию организации:</h3>&nbsp;@Html.TextBox("SearchTwo", "")
        <input type="submit" value="Поиск" />
</fieldset>
}

<br/>
<p>
    @Html.ActionLink("Добавить запись", "Create")
</p>
<table class="table-bordered" cellpadding="5" width="100%" align="center" style="font-size:14px">
    <tr>
        <th> Код </th>
        <th> Наименование продукции </th>
        <th> Всего произведено </th>
        <th> Год </th>
        <th> Квартал </th>
        <th> Название организации </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td><p>@Html.DisplayFor(modelItem => item.ReleaseID)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.TypesProduction.ProductionName)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.TotalRelease)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.Year)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.Quarter)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.Organization.OrganizationName)</p></td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.ReleaseID }) |
                @Html.ActionLink("Детали", "Details", new { id = item.ReleaseID}) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.ReleaseID })
            </td>
        </tr>
    }
</table>

<div style="text-align: center;">
    Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>