EnergyConsumptionRationing/Controllers/StandartExpensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnergyConsumptionRationing.Models;
using PagedList;


namespace EnergyConsumptionRationing.Controllers
{
    public class StandartExpensesController : Controller
    {
        private EnergyContext db = new EnergyContext();

        // GET: StandartExpenses
        public ActionResult Index(int? page, string SearchOne = "", string SearchTwo = "")
        {
            var query = from i in db.StandartExpense
                        where i.TypesProduction.ProductionName.StartsWith(SearchOne) && i.Quarter.ToString().StartsWith(SearchTwo)
                        select i;
            int PageSize = 10;
            int pageNumber = (page ?? 1);
            var sotorder = query.OrderBy(im => im.ExpenseID);
            return View(sotorder.ToPagedList(pageNumber, PageSize));
        }

        // GET: StandartExpenses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StandartExpense standartExpense = db.StandartExpense.Find(id);
            if (standartExpense == null)
            {
                return HttpNotFound();
            }
            return View(standartExpense);
        }

        // GET: StandartExpenses/Create
        public ActionResult Create()
        {
            ViewBag.OrganizationID = new SelectList(db.Organization, "OrganizationID", "OrganizationName");
            ViewBag.ProductionID = new SelectList(db.TypesProduction, "ProductionID", "ProductionName");
            return View();
        }

        // POST: StandartExpenses/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExpenseID,QuarterlyNormEnergyUnit,ProductionID,Year,Quarter,OrganizationID")] StandartExpense standartExpense)
        {
            if (ModelState.IsValid)
            {
                db.StandartExpense.Add(standartExpense);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OrganizationID = new SelectList(db.Organization, "OrganizationID", "OrganizationName", standartExpense.OrganizationID);
            ViewBag.ProductionID = new SelectList(db.TypesProduction, "ProductionID", "ProductionName", standartExpense.ProductionID);
            return View(standartExpense);
        }

        // GET: StandartExpenses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StandartExpense standartExpense = db.StandartExpense.Find(id);
            if (standartExpense == null)
            {
                return HttpNotFound();
            }
            ViewBag.OrganizationID = new SelectList(db.Organization, "OrganizationID", "OrganizationName", standartExpense.OrganizationID);
            ViewBag.ProductionID = new SelectList(db.TypesProduction, "ProductionID", "ProductionName", standartExpense.ProductionID);
            return View(standartExpense);
        }

        // POST: StandartExpenses/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExpenseID,QuarterlyNormEnergyUnit,ProductionID,Year,Quarter,OrganizationID")] StandartExpense standartExpense)
        {
            if (ModelState.IsValid)
            {
                db.Entry(standartExpense).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OrganizationID = new SelectList(db.Organization, "OrganizationID", "OrganizationName", standartExpense.OrganizationID);
            ViewBag.ProductionID = new SelectList(db.TypesProduction, "ProductionID", "ProductionName", standartExpense.ProductionID);
            return View(standartExpense);
        }

        // GET: StandartExpenses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StandartExpense standartExpense = db.StandartExpense.Find(id);
            if (standartExpense == null)
            {
                return HttpNotFound();
            }
            return View(standartExpense);
        }

        // POST: StandartExpenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StandartExpense standartExpense = db.StandartExpense.Find(id);
            db.StandartExpense.Remove(standartExpense);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnergyConsumptionRationing/Views/StandartExpenses/Create.cshtml
@model EnergyConsumptionRationing.Models.StandartExpense

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить запись</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <dl class="dl-horizontal">
            <dt>Название организации</dt>
            <dd>
                @Html.DropDownList("OrganizationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganizationID, "", new { @class = "text-danger" })
            </dd>

            <dt>Наименование продукции</dt>
            <dd>
                @Html.DropDownList("ProductionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductionID, "", new { @class = "text-danger" })
            </dd>

            <dt>Квартальная норма расхода теплоэнергии(кВт/ч)</dt>
            <dd>
                @Html.EditorFor(model => model.QuarterlyNormEnergyUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuarterlyNormEnergyUnit, "", new { @class = "text-danger" })
            </dd>

            <dt>Год(с 1800 до 2016)</dt>
            <dd>
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </dd>

            <dt>Квартал</dt>
            <dd>
                @Html.EditorFor(model => model.Quarter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quarter, "", new { @class = "text-danger" })
            </dd>
        </dl>
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnergyConsumptionRationing/Views/StandartExpenses/Delete.cshtml
@model EnergyConsumptionRationing.Models.StandartExpense

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Вы уверены, что хотите удалить запись?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Название организации</dt>
        <dd>@Html.DisplayFor(model => model.Organization.OrganizationName)</dd>

        <dt>Наименование продукции</dt>
        <dd>@Html.DisplayFor(model => model.TypesProduction.ProductionName)</dd>

        <dt>Квартальная норма расхода теплоэнергии(кВт/ч)</dt>
        <dd>@Html.DisplayFor(model => model.QuarterlyNormEnergyUnit)</dd>

        <dt>Год</dt>
        <dd>@Html.DisplayFor(model => model.Year)</dd>

        <dt>Квартал</dt>
        <dd>@Html.DisplayFor(model => model.Quarter)</dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    }
</div>

EnergyConsumptionRationing/Views/StandartExpenses/Details.cshtml
@model EnergyConsumptionRationing.Models.StandartExpense

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Детали</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Название организации</dt>
        <dd>@Html.DisplayFor(model => model.Organization.OrganizationName)</dd>

        <dt>Нименование продукции</dt>
        <dd>@Html.DisplayFor(model => model.TypesProduction.ProductionName)</dd>

        <dt>Квартальная норма расхода теплоэнергии(кВт/ч)</dt>
        <dd>@Html.DisplayFor(model => model.QuarterlyNormEnergyUnit)</dd>

        <dt>Год</dt>
        <dd>@Html.DisplayFor(model => model.Year)</dd>

        <dt>Квартал</dt>
        <dd>@Html.DisplayFor(model => model.Quarter)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать запись", "Edit", new { id = Model.ExpenseID }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>

EnergyConsumptionRationing/Views/StandartExpenses/Edit.cshtml
@model EnergyConsumptionRationing.Models.StandartExpense

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Реадктировать запись</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ExpenseID)

        <dl class="dl-horizontal">
            <dt>Название организации</dt>
            <dd>
                @Html.DropDownList("OrganizationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganizationID, "", new { @class = "text-danger" })
            </dd>

            <dt>Наименование продукции</dt>
            <dd>
                @Html.DropDownList("ProductionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductionID, "", new { @class = "text-danger" })
            </dd>

            <dt>Квартальная норма расхода теплоэнергии(кВт/ч)</dt>
            <dd>
                @Html.EditorFor(model => model.QuarterlyNormEnergyUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuarterlyNormEnergyUnit, "", new { @class = "text-danger" })
            </dd>

            <dt>Год(с 1800 до 2016)</dt>
            <dd>
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </dd>

            <dt>Квартал</dt>
            <dd>
                @Html.EditorFor(model => model.Quarter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quarter, "", new { @class = "text-danger" })
            </dd>
        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnergyConsumptionRationing/Views/StandartExpenses/Index.cshtml
@model PagedList.IPagedList<EnergyConsumptionRationing.Models.StandartExpense>
    @using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("/Content/PageList.css")" rel="stylesheet" type="text/css" />
<h2>Норма расхода теплоэнергии</h2>

@using (Html.BeginForm("Index", "StandartExpenses", FormMethod.Get))
{
    <fieldset>
        <h3 style="font-size:14px">Поиск по наименованию продукции:</h3>&nbsp;@Html.TextBox("SearchOne", "")
        <input type="submit" value="Поиск" />
        &ensp;
        <h3 style="font-size:14px">Поиск по номеру квартала:</h3>&nbsp;@Html.TextBox("SearchTwo", "")
        <input type="submit" value="Поиск" />
    </fieldset>
}

<br />

<p>
    @Html.ActionLink("Добавить запись", "Create")
</p>
<table class="table-bordered" cellpadding="5" width="100%" align="center" style="font-size:14px">
    <tr>
        <th> Код </th>
        <th> Квартальная норма расхода теплоэнергии(кВт/ч)</th>
        <th> Наименование продукции </th>
        <th> Год </th>
        <th> Квартал </th>
        <th> Название организации </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td><p>@Html.DisplayFor(modelItem => item.ExpenseID)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.QuarterlyNormEnergyUnit)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.TypesProduction.ProductionName)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.Year)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.Quarter)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.Organization.OrganizationName)</p></td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.ExpenseID }) |
                @Html.ActionLink("Детали", "Details", new { id = item.ExpenseID }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.ExpenseID })
            </td>
        </tr>
    }
</table>
<div style="text-align: center;">
    Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>