EnergyConsumptionRationing/Models/Organization.cs
namespace EnergyConsumptionRationing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Organization")]
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            ConsumedRelease = new HashSet<ConsumedRelease>();
            ReleaseProducts = new HashSet<ReleaseProducts>();
            StandartExpense = new HashSet<StandartExpense>();
        }

        public int OrganizationID { get; set; }

        [StringLength(30)]
        public string OrganizationName { get; set; }

        [StringLength(30)]
        public string FormOwnership { get; set; }

        [StringLength(30)]
        public string Address { get; set; }

        [StringLength(30)]
        public string NameLeader { get; set; }

        [Range(1, 10000000000, ErrorMessage = "The data is incorrect")]
        public int? PhoneLeader { get; set; }

        [StringLength(30)]
        public string NameEngineer { get; set; }

        [Range(1, 10000000000, ErrorMessage = "The data is incorrect")]
        public int? PhoneEngineer { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumedRelease> ConsumedRelease { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseProducts> ReleaseProducts { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandartExpense> StandartExpense { get; set; }
    }
}

EnergyConsumptionRationing/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnergyConsumptionRationing.Models;
using PagedList;

namespace EnergyConsumptionRationing.Controllers
{
    public class OrganizationsController : Controller
    {
        private EnergyContext db = new EnergyContext();

        // GET: Organizations
        public ActionResult Index(int? page, string Search = "")
        {
            var query = from or in db.Organization
                        where or.OrganizationName.StartsWith(Search)
                        select or;
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var sotorder = query.OrderBy(t => t.OrganizationID);
            return View(sotorder.ToPagedList(pageNumber, pageSize));
        }

        // GET: Organizations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organization.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

        // GET: Organizations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Organizations/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrganizationID,OrganizationName,FormOwnership,Address,NameLeader,PhoneLeader,NameEngineer,PhoneEngineer")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Organization.Add(organization);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(organization);
        }

        // GET: Organizations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organization.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

        // POST: Organizations/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrganizationID,OrganizationName,FormOwnership,Address,NameLeader,PhoneLeader,NameEngineer,PhoneEngineer")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Entry(organization).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(organization);
        }

        // GET: Organizations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organization.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

        // POST: Organizations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Organization organization = db.Organization.Find(id);
            db.Organization.Remove(organization);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnergyConsumptionRationing/Views/Organizations/Create.cshtml
@model EnergyConsumptionRationing.Models.Organization

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить запись</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <dl class="dl-horizontal">
            <dt>Название организации</dt>
            <dd>
                @Html.EditorFor(model => model.OrganizationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationName, "", new { @class = "text-danger" })
            </dd>

            <dt>Форма собственности</dt>
            <dd>
                @Html.EditorFor(model => model.FormOwnership, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FormOwnership, "", new { @class = "text-danger" })
            </dd>

            <dt>Адрес</dt>
            <dd>
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </dd>

            <dt>Ф.И.О. руководителя</dt>
            <dd>
                @Html.EditorFor(model => model.NameLeader, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameLeader, "", new { @class = "text-danger" })
            </dd>

            <dt>Телефон руководителя</dt>
            <dd>
                @Html.EditorFor(model => model.PhoneLeader, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneLeader, "", new { @class = "text-danger" })
            </dd>

            <dt>Ф.И.О. главного инженера</dt>
            <dd>
                @Html.EditorFor(model => model.NameEngineer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameEngineer, "", new { @class = "text-danger" })
            </dd>

            <dt>Телефон главного инженера</dt>
            <dd>
                @Html.EditorFor(model => model.PhoneEngineer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneEngineer, "", new { @class = "text-danger" })
            </dd>
        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnergyConsumptionRationing/Views/Organizations/Delete.cshtml
@model EnergyConsumptionRationing.Models.Organization

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Вы уверены, что хотите удалить запись?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Название организации</dt>
        <dd>@Html.DisplayFor(model => model.OrganizationName)</dd>

        <dt>Форма собственности</dt>
        <dd>@Html.DisplayFor(model => model.FormOwnership)</dd>

        <dt>Адрес</dt>
        <dd>@Html.DisplayFor(model => model.Address)</dd>

        <dt>Ф.И.О. руководителя</dt>
        <dd>@Html.DisplayFor(model => model.NameLeader)</dd>

        <dt>Телефон руководителя</dt>
        <dd>@Html.DisplayFor(model => model.PhoneLeader)</dd>

        <dt>Ф.И.О. главного инженера</dt>
        <dd>@Html.DisplayFor(model => model.NameEngineer)</dd>

        <dt>Телефон главного инженера</dt>
        <dd>@Html.DisplayFor(model => model.PhoneEngineer)</dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    }
</div>

EnergyConsumptionRationing/Views/Organizations/Details.cshtml
@model EnergyConsumptionRationing.Models.Organization

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Детали</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Название организации</dt>
        <dd>@Html.DisplayFor(model => model.OrganizationName)</dd>

        <dt>Форма собственности</dt>
        <dd>@Html.DisplayFor(model => model.FormOwnership)</dd>

        <dt>Адрес</dt>
        <dd>@Html.DisplayFor(model => model.Address)</dd>

        <dt>Ф.И.О. руководителя</dt>
        <dd>@Html.DisplayFor(model => model.NameLeader)</dd>

        <dt>Телефон руководителя</dt>
        <dd>@Html.DisplayFor(model => model.PhoneLeader)</dd>

        <dt>Ф.И.О. главного инженера</dt>
        <dd>@Html.DisplayFor(model => model.NameEngineer)</dd>

        <dt>Телефон главного инженера</dt>
        <dd>@Html.DisplayFor(model => model.PhoneEngineer)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать запись", "Edit", new { id = Model.OrganizationID }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>

EnergyConsumptionRationing/Views/Organizations/Edit.cshtml
@model EnergyConsumptionRationing.Models.Organization

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактировать запись</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrganizationID)

        <dl class="dl-horizontal">
            <dt>Название организации</dt>
            <dd>
                @Html.EditorFor(model => model.OrganizationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationName, "", new { @class = "text-danger" })
            </dd>

            <dt>Форма собственности</dt>
            <dd>
                @Html.EditorFor(model => model.FormOwnership, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FormOwnership, "", new { @class = "text-danger" })
            </dd>

            <dt>Адрес</dt>
            <dd>
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </dd>

            <dt>Ф.И.О. руководителя</dt>
            <dd>
                @Html.EditorFor(model => model.NameLeader, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameLeader, "", new { @class = "text-danger" })
            </dd>

            <dt>Телефон руководителя</dt>
            <dd>
                @Html.EditorFor(model => model.PhoneLeader, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneLeader, "", new { @class = "text-danger" })
            </dd>

            <dt>Ф.И.О. главного инженера</dt>
            <dd>
                @Html.EditorFor(model => model.NameEngineer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameEngineer, "", new { @class = "text-danger" })
            </dd>

            <dt>Телефон главного инженера</dt>
            <dd>
                @Html.EditorFor(model => model.PhoneEngineer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneEngineer, "", new { @class = "text-danger" })
            </dd>
        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnergyConsumptionRationing/Views/Organizations/Index.cshtml
@model  PagedList.IPagedList<EnergyConsumptionRationing.Models.Organization>
    @using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("/Content/PagedList.css")" rel = "stylesheet" type = "text/css"/>

<h2>Организации</h2>
@using (Html.BeginForm("Index", "Organizations", FormMethod.Get))
{
    <fieldset>
        <h3 style="font-size:14px">Поиск по названию организации:</h3>&nbsp;@Html.TextBox("Search", "")
        <input type="submit" value="Поиск"/>
    </fieldset>
}
<p>
    @Html.ActionLink("Добавить запись", "Create")
</p>
<table class="table-bordered" cellpadding="5" width="100%" align="center" style="font-size:14px">
    <tr>
        <th>Код</th>
        <th>Название организации</th>
        <th>Форма собственности</th>
        <th>Адресс</th>
        <th>Ф.И.О. руководителя</th>
        <th>Телефон руководителя</th>
        <th>Ф.И.О. главного инженера</th>
        <th>Телефон главного инженера</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td><p>@Html.DisplayFor(modelItem => item.OrganizationID)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.OrganizationName)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.FormOwnership)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.Address)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.NameLeader)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.PhoneLeader)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.NameEngineer)</p></td>
            <td><p>@Html.DisplayFor(modelItem => item.PhoneEngineer)</p></td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.OrganizationID }) |
                @Html.ActionLink("Детали", "Details", new { id = item.OrganizationID }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.OrganizationID })
            </td>
        </tr>
    }
</table>

<div style="text-align:center;">
    Страница @(Model.PageCount < Model.PageNumber ? 0:Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page}))
</div>